# Site settings
title: "Hausärztliche Gemeinschaftspraxis"
author: "Hausärztliche Gemeinschaftspraxis"
email: info@hausarzt-bgd.de
description: home.description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hausarzt-bgd.github.io"

github_username: "hausarzt-bgd"
linkedin: " "
xing: " "

exclude: ["site_publish.sh", ".jekyll-cache"]  

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["de"]
exclude_from_localizations: ["css", "js", "img", "fonts", "download", "favicon.ico"]
default_locale_in_subfolder: false
